# Generated by Django 4.0.5 on 2022-10-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=50)),
                ('ticket_from', models.CharField(max_length=100)),
                ('ticket_to', models.CharField(max_length=100)),
                ('depart', models.DateField()),
                ('Return', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=150)),
                ('strdate', models.DateField()),
                ('enddate', models.DateField()),
                ('adults1', models.IntegerField()),
                ('children1', models.IntegerField()),
                ('f_name', models.CharField(max_length=150)),
                ('ph_num', models.CharField(max_length=10)),
                ('hot_cat', models.CharField(max_length=150)),
                ('lnd_trns', models.CharField(max_length=150)),
                ('transport', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('con_number', models.CharField(max_length=10)),
            ],
        ),
    ]
