# Generated by Django 4.0 on 2022-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('one-way', 'ONE-WAY'), ('return', 'RETURN'), ('multi-city', 'MULTI-CITY')], max_length=50)),
                ('ticket_from', models.CharField(max_length=100)),
                ('ticket_to', models.CharField(max_length=100)),
                ('depart', models.DateField()),
                ('Return', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(null=True)),
                ('travel_class', models.CharField(choices=[('first-class/1A', 'First-Class/1A'), ('ac2tier/2A', 'Ac2Tier/2A'), ('ac3tier/3A', 'Ac3Tier/3A'), ('ec class/economyclass', 'Ec Class/Economy CLass'), ('ac chair car', 'Ac Chair Car'), ('sleeper class', 'Sleeper Class'), ('second class', 'Second Class'), ('general', 'General')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BookForm',
        ),
    ]
