# Generated by Django 4.0.5 on 2022-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone_no',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ph_num',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='con_number',
            field=models.CharField(max_length=13),
        ),
    ]
