# Generated by Django 4.0 on 2022-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_book_delete_bookform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ticket_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='travel_class',
            field=models.CharField(max_length=100),
        ),
    ]
