# Generated by Django 4.0 on 2022-03-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='full_name',
        ),
    ]
